# Generated by Django 2.1.7 on 2019-04-11 10:47

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('pia_manager_name', models.TextField()),
                ('pia_manager_email', models.TextField()),
                ('activity_manager_name', models.TextField()),
                ('activity_manager_email', models.TextField()),
                ('date', models.DateTimeField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'activity',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='team.Activity')),
            ],
            options={
                'db_table': 'answer',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.TextField()),
                ('name', models.TextField()),
                ('impact_level', models.IntegerField()),
                ('risk', models.TextField()),
                ('likelihood', models.IntegerField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='team.Activity')),
            ],
            options={
                'db_table': 'asset',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('inner_id', models.IntegerField()),
            ],
            options={
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='QuestionaryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'questionary_type',
            },
        ),
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('role', models.TextField()),
                ('email', models.TextField()),
                ('part', models.TextField()),
                ('feedback', models.TextField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='team.Activity')),
            ],
            options={
                'db_table': 'stakeholder',
            },
        ),
        migrations.CreateModel(
            name='Swimlane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swimlane_json', django_mysql.models.JSONField(blank=True, default=dict, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='team.Activity')),
            ],
            options={
                'db_table': 'swimlane',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.TextField()),
                ('password', models.TextField()),
                ('permission_level', models.IntegerField()),
                ('name', models.TextField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='team.Activity')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='questionary_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='team.QuestionaryType'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='team.Question'),
        ),
    ]
