# Generated by Django 2.1.7 on 2019-03-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('pia_manager_name', models.CharField(max_length=20)),
                ('pia_manager_email', models.CharField(max_length=35)),
                ('activity_manager_name', models.CharField(max_length=20)),
                ('activity_manager_email', models.CharField(max_length=35)),
                ('date', models.DateTimeField()),
                ('description', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'activity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionaryAnswer',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('questionary_id', models.IntegerField()),
                ('questionary_ans', models.CharField(max_length=512)),
                ('activity_id', models.CharField(max_length=512)),
                ('questionary_type', models.IntegerField()),
                ('questionary_type_id', models.IntegerField()),
            ],
            options={
                'db_table': 'questionary_answer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionaryTemplate',
            fields=[
                ('questionary_id', models.AutoField(primary_key=True, serialize=False)),
                ('questionary_description', models.CharField(max_length=512)),
                ('questionary_type', models.IntegerField()),
                ('questionary_type_id', models.IntegerField()),
            ],
            options={
                'db_table': 'questionary_template',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('permission_level', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('activity_id', models.IntegerField()),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
