# Generated by Django 2.1.7 on 2019-05-04 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('pia_manager_name', models.TextField()),
                ('pia_manager_email', models.TextField()),
                ('activity_manager_name', models.TextField()),
                ('activity_manager_email', models.TextField()),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'activity',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='team.Activity')),
            ],
            options={
                'db_table': 'answer',
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pii_id', models.IntegerField()),
                ('asset_type', models.TextField(blank=True, null=True)),
                ('asset_id', models.IntegerField(blank=True, null=True)),
                ('probability', models.IntegerField(blank=True, null=True)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='team.Activity')),
            ],
            options={
                'db_table': 'evaluation',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='team.Activity')),
            ],
            options={
                'db_table': 'participant',
            },
        ),
        migrations.CreateModel(
            name='Pii',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('value', models.IntegerField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='team.Activity')),
            ],
            options={
                'db_table': 'pii',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'process',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('inner_id', models.IntegerField()),
            ],
            options={
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='QuestionaryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'questionary_type',
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'risk',
            },
        ),
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('role', models.TextField()),
                ('email', models.TextField()),
                ('part', models.TextField()),
                ('feedback', models.TextField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='team.Activity')),
            ],
            options={
                'db_table': 'stakeholder',
            },
        ),
        migrations.CreateModel(
            name='Swimlane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swimlane_json', models.TextField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='team.Activity')),
            ],
            options={
                'db_table': 'swimlane',
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='team.Activity')),
            ],
            options={
                'db_table': 'system',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.TextField()),
                ('password', models.TextField()),
                ('name', models.TextField()),
                ('permission_level', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='ProcessHasParticipant',
            fields=[
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='team.Process')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='team.Participant')),
            ],
            options={
                'db_table': 'process_has_participant',
            },
        ),
        migrations.CreateModel(
            name='ProcessHasPii',
            fields=[
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='team.Process')),
                ('pii', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='team.Pii')),
            ],
            options={
                'db_table': 'process_has_pii',
            },
        ),
        migrations.CreateModel(
            name='ProcessHasSystem',
            fields=[
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='team.Process')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='team.System')),
            ],
            options={
                'db_table': 'process_has_system',
            },
        ),
        migrations.CreateModel(
            name='UserHasActivity',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='team.User')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='team.Activity')),
            ],
            options={
                'db_table': 'user_has_activity',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='questionary_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='team.QuestionaryType'),
        ),
        migrations.AddField(
            model_name='process',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='team.Activity'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='risk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='team.Risk'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='team.Question'),
        ),
        migrations.AlterUniqueTogether(
            name='userhasactivity',
            unique_together={('user', 'activity')},
        ),
        migrations.AlterUniqueTogether(
            name='processhassystem',
            unique_together={('process', 'system')},
        ),
        migrations.AlterUniqueTogether(
            name='processhaspii',
            unique_together={('process', 'pii')},
        ),
        migrations.AlterUniqueTogether(
            name='processhasparticipant',
            unique_together={('process', 'participant')},
        ),
    ]
